# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Making NYC Streets Safer - Analyzing Traffic Accidents Dataset
description: Our webpage aims to raise awareness and explore solutions to make New York City streets safer by analyzing the latest traffic accidents dataset for trends, patterns, and contributing factors. Our goal is to identify potential initiatives to reduce the number of accidents and improve road safety in NYC.
url: "https://jens-create.github.io/"

#for github pages - whenever you push to the repo below line should be uncommented.
baseurl: "socialdata2023"

#for local development - only change temporarily.
#baseurl: ""


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
