# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Making NYC Streets Safer - Analyzing Traffic Accidents Dataset
description: This webpage aims to raise awareness about traffic accidents in New York City and explore ways to make the streets safer for everyone. We will dive into the latest traffic accidents dataset and analyze the trends, patterns, and factors that contribute to these accidents. By understanding the data, we hope to identify potential solutions and initiatives that can help reduce the number of traffic accidents and improve road safety in NYC.
url: "https://jens-create.github.io/socialdata2023"

#for github pages - whenever you push to the repo below line should be uncommented.
baseurl: "socialdata2023"

#for local development - only change temporarily.
#baseurl: ""


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
